# Generated by Django 5.0.7 on 2024-11-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eafit_comercio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
