# Generated by Django 5.0.7 on 2024-11-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
